### ISSUE TITLE
Cagada en sitio Wordpress

### ISSUE THREAD

**Issue by Lynn-Lied** [face2dance/Face-2-Dance#2]
Manu! Ayudaa!!!!

La he cagado :(

![borrar-1](https://cloud.githubusercontent.com/assets/19736285/15792376/7d760dc8-29a2-11e6-95d9-31e396420205.jpg)
![borrar-2](https://cloud.githubusercontent.com/assets/19736285/15792377/7d7c884c-29a2-11e6-9946-1e2bad083415.jpg)

**Comment by face2dance** [comment]
Arreglado el chicharrón... Manitas creativas!!!
